### ISSUE TITLE
Talking to NPC while getting 8 bits

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#49] opened 2015-12-11 02:07 UTC
I managed to talk to an NPC (the girl in the classroom) while the 8th bit was creating a cube, then Gomez didn't jump to get the cube, but the "item get" music was still playing... I had to jump to the floating cube to get it.

... I really should record while testing. ^^;;

**Comment by Gimlao** [comment] 2015-12-11 02:16
I remembered that, since I'm running Win10, the last 10 minutes will be recorded (Win+Alt+G) : 
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/FEZ%2011_12_2015%2003_08_33.mp4 :D

I was also testing #4 and #48.

**Comment by renaudbedard** [comment] 2016-02-12 04:42
I see that the bug happens in the video, but I tried to reproduce it and couldn't get it. If you talk to an NPC and force a "walk to" animation by being too close to it, the cube-assemble event waits patiently for the conversation to be done before triggering and I don't get an issue.
I think it's a one-frame thing where you have to trigger the NPC conversation in the very same frame that the cube assembly starts, which is super hard to pull off... I might disregard this bug. :(

**Comment by flibitijibibo** [comment] 2016-05-23 15:54
Can you still get this to happen with frame-perfect timing? If it's too hard to get again then we'll probably close this as 'too obscure'.

**Comment by flibitijibibo** [comment] 2016-05-23 16:15
Closing due to old age, the obscurity of the bug (frame-perfect!), and that it actually seems to handle things relatively gracefully - I'd be worried if it produced 2 cubes, but it at least knows not to count both cutscenes as cubes. Feel free to practice this one for glitch showcases in the future :P

**Closed as completed by flibitijibibo** 2016-05-23 16:15 UTC
Labels: Can't Repro, Progression, Dialog
