### ISSUE TITLE
Soft lock with 32 cube dot text and landing on a ledge.

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#29] opened 2015-12-02 10:00 UTC
Collected my 32nd second cube in the Rosetta Stone room. Dropped from the large pillar and grabbed onto the corner of the small pillar's ledge at the exact same time dot came out to do her 32 cube speech. Resulted in dot being stuck mid animation and Gomez being stuck on the ledge, unable to move. Was only able to enter pause menu. Had to reset the game.

**Comment by Gyoo** [comment] 2015-12-02 13:12
Interesting, because 0x0ade already fixed that in FEZmod for the 16 cobes text. I encountered this softlock in the bouncing mushrooms room.

**Comment by 0x0ade** [comment] 2015-12-03 08:13
Actually, I've fixed it for the mushrooms and any DOT text. Renaud has merged the bugfix for the Bounce action: https://github.com/AngelDE98/FEZMod/blob/master/FEZ.Mod.mm/FezGame/Components/Actions/Bounce.cs

(Selfnote: I can actually make the check more performant by not calling ServiceHelper.Get<IGameStateManager>() that often)

**Comment by renaudbedard** [comment] 2015-12-12 03:45
I haven't been able to reproduce this... but I trust you!

I made a change to the DOT talk stuff so that I don't think can soft-lock anymore. If DOT dialogue is visible, it should allow you to press B and dismiss it no matter what.

Let me know if you're able to repro it. It doesn't have to be in this room, and doesn't have to be this cube or this test. Any of the random DOT appearances (first anti-cube, 4/8/16/32/64 cubes) would trigger it, in any room.

**Closed as completed by renaudbedard** 2015-12-12 03:45 UTC
