### ISSUE TITLE
"Saving" sign doesn't disappear and permanently blinks

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#107] opened 2016-07-11 17:36 UTC
I have updated v1.11 to current fna-unstable, and as the result I have permanent "Saving" sign in most cases. This red square rotates permanently (and blinks a little bit):
http://veg.by/z/2016-07-11-20-10-59-03bd715b.png
http://veg.by/z/2016-07-11-20-11-10-d36dc5c9.png
http://veg.by/z/2016-07-11-20-29-48-6bbec104.png

I have tried to restart the game more than 10 times. As the result only two times the game had hidden this icon as it have to be. 8/10 times this sign doesn't disappear.

You can download my save states here: http://veg.by/files/temp/fez-savestates.7z

**Comment by flibitijibibo** [comment] 2016-07-11 17:37
What happens when you enable singlethreaded mode in the game options?

**Comment by vrubleg** [comment] 2016-07-11 17:54
It doesn't help. (I have restarted the game after changing this setting).

I've used Process Monitor to see what does game write all the time, but it seems that it writes only steam overlay log and nothing more: http://veg.by/z/2016-07-11-20-52-13-606b8258.png

My hardware: http://veg.by/z/2016-07-11-21-06-23-7762d9d2.png

**Comment by flibitijibibo** [comment] 2016-07-11 18:21
Does the GameOverlayRenderer.log say anything interesting? Looking at the IO log it does write the save, but for some reason it's not happy about something Steam-related (possibly cloud?).

**Comment by flibitijibibo** [comment] 2016-07-11 18:32
One more thing to look at - anything in the log file? It's in `%APPDATA%\FEZ\`.

**Comment by renaudbedard** [comment] 2016-07-11 18:33
He already put the log files in the .7z file he linked, there's nothing of
interest in there X(

**Comment by vrubleg** [comment] 2016-07-11 18:34
> Does the GameOverlayRenderer.log say anything interesting?

It says such things:

```
Mon Jul 11 18:22:13 2016 UTC - Disabling overlay for 2 seconds (10 seconds since last frame from ui process was seen)
Mon Jul 11 18:22:15 2016 UTC - Disabling overlay for 2 seconds (12 seconds since last frame from ui process was seen)
Mon Jul 11 18:22:17 2016 UTC - Disabling overlay for 2 seconds (14 seconds since last frame from ui process was seen)
Mon Jul 11 18:22:20 2016 UTC - Disabling overlay for 2 seconds (16 seconds since last frame from ui process was seen)
```

(In-game Steam overlay is disabled in Steam settings).

**Comment by flibitijibibo** [comment] 2016-07-11 18:36
Ah-ha! That is indeed the repro case - if we disable the overlay there's constant failure on the screen. Now I have a place to work from, thanks for the monitor data!

**Comment by vrubleg** [comment] 2016-07-11 18:42
Ok, it seems that you're right. I've enabled steam overlay and now this square disappears as it have to be.

BTW, I think that it is better to block "achievements" menu item when Steam overlay is disabled, because this item also doesn't work in this case.

**Comment by flibitijibibo** [comment] 2016-07-11 18:42
Good point, will add that to the next update as well.

**Comment by flibitijibibo** [comment] 2016-07-11 18:56
Got it - it was a regression from moving to Steamworks.NET. The problem was that I rewrote the Steamworks integration line-by-line when the previous lib (which was very poor for reasons like this) was doing some stat acquisition behind the game's back. Requesting the stats ourselves like we're supposed to fixes the issue.

This and the achievement option silencing will be in the next update.

**Comment by flibitijibibo** [comment] 2016-07-11 19:14
Both fixes are in repo, will be live whenever Renaud does his next upload.

**Closed as completed by flibitijibibo** 2016-07-11 19:14 UTC
