### ISSUE TITLE
Unable to grab rotating platform

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#58] opened 2015-12-13 14:03 UTC
When jumping from this ledge, it is sometimes impossible to grab onto that rotating platform to the right.

![7](https://cloud.githubusercontent.com/assets/16115136/11767343/ffe2b1dc-a16f-11e5-9d5a-eda974530d03.png)

**Comment by renaudbedard** [comment] 2015-12-14 05:34
I'll just mark this as a duplicate of #33 and put all ledge + rotating spinblock problems in there.

**Closed as completed by renaudbedard** 2015-12-14 05:34 UTC
