### ISSUE TITLE
Letters can float in the Megalith room

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#61] opened 2015-12-15 14:08 UTC
I put a letter on top of another here : 
![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/floating_letter1.png)

Then I discovered that it was actually floating : 
![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/floating_letter2.png)

**Comment by Gimlao** [comment] 2015-12-15 14:13
Also, when holding a letter, then rotating, this letter can rotate itself one more time in Gomez hands...

**Comment by Gimlao** [comment] 2015-12-15 14:26
It seems that the Heart Cube is not centered, not really an issue, but still weird : 
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/FEZ%2015_12_2015%2015_24_35.mp4

:3

**Comment by renaudbedard** [comment] 2016-03-01 02:59
Can you reproduce this at will? I tried but couldn't.
Besides, I know that the crate/block manipulation is sort of wonky in the puzzle rooms... would love to fix it but a lot of it just comes with the wonky physics of FEZ. It's really hard to fix these without breaking a million other things...

So unless I can reproduce this easily/quickly, I don't have big hopes of fixing it. Sorry!

**Comment by flibitijibibo** [comment] 2016-05-23 15:52
Closing due to old age. For physics boogs we'll probably be focusing more on the predictive physics for the 17ms timestep and not much else, so we can actually ship this at some point...

**Closed as completed by flibitijibibo** 2016-05-23 15:52 UTC
Labels: Can't Repro, Physics
