### ISSUE TITLE
Freeze when exiting a room in Gomez village

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#17] opened 2015-12-02 01:01 UTC
Exiting this room :
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/room.png

```
(02:00:00.848) [Content] WARNING : Couldn't find asset in references : Art Objects\newhouse_AAO
(02:00:00.849) [Content] WARNING : Couldn't find asset in references : Art Objects\newhouse_AAO
(02:00:00.849) [Content] WARNING : Couldn't find asset in references : Art Objects\newhouse_AAO
(02:00:00.849) [Content] WARNING : Couldn't find asset in references : Art Objects\newhouse_AAO
(02:00:00.850) [Content] WARNING : Couldn't find asset in references : Sounds\Wildlife\BirdTakeoff
```

I had to kill FEZ.exe using Ctrl+Shift+Esc.

**Comment by Gimlao** [comment] 2015-12-02 01:10
Can't reproduce...

**Comment by renaudbedard** [comment] 2015-12-02 01:37
Very strange... if someone can reproduce that would be awesome.

**Comment by ghost** [comment] 2016-01-11 19:33
I've had this happen to me on a brand new run, resulted in a crash. After that I was unable to reproduce it, unfortunately. Identical output as above.

Above happened on Linux/Nvidia.

**Comment by renaudbedard** [comment] 2016-01-11 20:17
So what's the runthrough of what made it happen? 3D village, go into the room screenshoted in the OP, exit the room, crash/hang?

**Comment by ghost** [comment] 2016-01-11 20:26
Exactly that. Doesn't seem to happen after restarting the game, and I cnr on a second run immediately after that (I didn't try wiping everything again to start from a clean slate though).

**Comment by renaudbedard** [comment] 2016-01-11 20:32
Annoying... but thanks for the details, I'll take a closer look!

**Comment by flibitijibibo** [comment] 2016-05-23 15:58
This might have been passively fixed by the various threading changes and other such items, so I'll pretend that this is what it was... if it turns out I'm wrong, @soeb: Try to grab a thread dump with Ctrl+\ and that should give us everything we need.

**Closed as completed by flibitijibibo** 2016-05-23 15:58 UTC
Labels: Can't Repro, Assets, Progression
