### ISSUE TITLE
Save Management + Start New Game Glitch

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#13] opened 2015-12-02 00:01 UTC
When playing, changing slot or clearing a slot, then starting a new game will result in this :

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/wtf.png

Before that, Gomez room will be shown without the zoom-in transition, and we will need to alt-tab (forcing the pause menu to appear) to be able to do anything.

**Comment by renaudbedard** [comment] 2015-12-09 04:55
Should be fixed now, was able to reproduce but only in Release, because it was a threading race-condition issue. Let me know if there are still oddities related to clearing/switching saves (apart from #35).

**Closed as completed by renaudbedard** 2015-12-09 04:55 UTC
