### ISSUE TITLE
Boiler room not becoming gold on the map

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#81] opened 2016-01-07 11:56 UTC
Title explains it. Got the map and the anticube from the Boiler room in villageville. Still says there is a secret in the room on the minimap. 

I will add to this post should it happen in other places.

**Comment by renaudbedard** [comment] 2016-01-07 15:05
Duplicate of #46.

**Closed as completed by renaudbedard** 2016-01-07 15:05 UTC
