### ISSUE TITLE
Dot can be heard talking while not being on screen

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#45] opened 2015-12-08 17:49 UTC
After the very first Dot dialog, I paused, resumed, then examined the sign next to Gomez house : 
Dot dialog SFX started to play (+ infinite loop).

I had to return into Gomez house to stop it.

**Comment by renaudbedard** [comment] 2016-02-12 04:09
Are you able to reproduce this reliably? I just tried and couldn't get it to trigger. Let me know if there's some kind of trick...

**Comment by flibitijibibo** [comment] 2016-05-23 15:55
Did this ever happen again? If we can nail down exact timings then I should be able to trace when it attempts to play the Dot sfx, but otherwise it might be one of those super precise things that we won't be able to fix for 1.12.

**Comment by flibitijibibo** [comment] 2016-06-03 20:10
Couldn't get this one to happen either... I don't even think this one loops, so it may have been an issue on FNA's part.

Closing due to old age, though I'd like to know if it can be repro'd at all.

**Closed as completed by flibitijibibo** 2016-06-03 20:10 UTC
Labels: Can't Repro, Dialog
