### ISSUE TITLE
Real Fullscreen Mode

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#119] opened 2016-07-22 13:18 UTC
New version of the game uses virtual resolutions. Actually, the game always uses maximum possible resolution of the primary display. That's nice that changing resolution works so quick, but there are some flaws.

It is important when screen recording software is used. For example, if I would like to record a 16:9 video (which is better for YouTube), but my display is 16:10, I can't do it. The image will be stretched to 1920×1200 when I choose 1920×1080 or even 1280×720. The other problem that capturing and encoding of 1920×1200 is much slower, than capturing and encoding of 1280×720. It causes noticeable and frequent frame drops.

It would be nice to have the "RealFullscreen" (or "EmulateFullscreen" with opposite meaning) setting at least in the settings file.

**Comment by flibitijibibo** [comment] 2016-07-22 13:21
This is more a problem with FNA rather than FEZ. FNA is what ultimately makes the final call on how fullscreen is done, so you'd have to look in the SDL2_FNAPlatform.cs to get what you want.

That said, I've never really found any measurable value for that fullscreen mode outside of accuracy needed for cycle-accurate emulators, so you may just want to edit Settings and run in a window, which OBS should be able to handle (it does on Linux, anyway...).

This is a WONTFIX but mostly because it's not FEZ that deals with this.

**Closed as completed by flibitijibibo** 2016-07-22 13:21 UTC
Labels: WONTFIX

**Comment by vrubleg** [comment] 2016-07-28 21:27
Virtual resolutions cause too much unnecessary side effects when non-native resolution is used.
- The game ignores preserving aspect ratio (“Maintain Aspect Ratio” in the GPU driver settings).
- Steam and FRAPS make screenshots with invalid size or/and proportions, for example, when I'm using 1280×720, but my native resolution is 1920×1200. As the result Steam's built-in screenshoter will take a blurry 1920×1200 screenshot, not 1280×720.
- Screen recording software have the same problem.

I believe that each of these side effects can be considered as a bug. Maybe it is better to use the Real Fullscreen by default, as it was in the previous version of the game.

I'm just trying to explain that current implementation of non-native resolutions support is a bit weird and have some non-obvious flaws. And that's strange, that the new version of the game has the separate Borderless Windowed mode (when can it be useful?), but it doesn't have the Real Fullscreen mode anymore.

**Comment by flibitijibibo** [comment] 2016-07-28 21:52
Not a bug, sorry. Implement it in FNA as an environment variable if you want it that badly:

https://github.com/FNA-XNA/FNA

Here's your test suite:

http://www.flibitijibibo.com/index.php?page=Portfolio/Tools#01_FNA.txt

**Comment by flibitijibibo** [comment] 2016-07-29 02:47
To give a better starting point, you'll want to start here:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L225

This sets the native window size, but you'll have to align it with the GLDevice's backbuffer size if you want the exclusive fullscreen size to be the same as the backbuffer size, which would be the same in fullscreen modes not associated with supersampled graphics modes:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/OpenGLDevice.cs#L761

The condition you have to worry about is the window size misaligning with the backbuffer size, which we check here:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/OpenGLDevice.cs#L4101

The tough part is that exclusive fullscreen isn't reported immediately by window managers (be it Win32, X11, etc.), and worse, you have to be sure that the window you're exclusively catching is correct, per the screenDeviceName that you're assigning the window to in ApplyWindowChanges; otherwise you end up doing a lot of work on a display that you hadn't intended to capture to begin with.

But, if you can make an `FNA_WINDOW_EXCLUSIVE_FULLSCREEN=1` that consistently sets the display mode for the right display that avoids redundant backbuffers and does not display data outside the game window for window managers that simulate non-native resolutions for windows within a display server, it should be feasible to skip the borderless centered window while also getting the performance issues that we've been getting with the FULLSCREEN_DESKTOP setup on Intel Windows drivers.

For additional help, some previous flibitQA members who might be able to help: @sulix @johndrinkwater @khbecker @meklu And some prior FNA contributors: @nickgravelyn @3vil @BlueLineGames and a couple more from the old FNA-MGHistory. If any of you guys feel like chipping in, go for it!

**Comment by renaudbedard** [comment] 2016-08-05 12:32
A part of this bug was addressed by @flibitijibibo yesterday : when setting a fullscreen mode that doesn't match the display's aspect ratio, the game adds black bars so that the output isn't distorted. :)

**Comment by vrubleg** [comment] 2016-08-05 13:45
Nice news! https://github.com/renaudbedard/fez-1.12-issues/issues/108 is the ticket about preserving aspect ratio =)
