### ISSUE TITLE
Crash after several restarts on speedrun mode

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#149] opened 2016-08-31 18:45 UTC
I was doing speedrun attempts earlier today when I got a sudden crash after restarting the run several times using the "Reset run" menu.

Here's the log :

```
(14:58:21.593) [FNA] INFORMATION : Controller 0: XInput Controller
(14:58:22.336) [Version] INFORMATION : 1.12, Build Date : 2016-08-20 14:50:53
(14:58:22.554) [FNA] INFORMATION : IGLDevice: OpenGLDevice
(14:58:22.554) [FNA] INFORMATION : OpenGL Device: AMD Radeon HD 7900 Series
(14:58:22.554) [FNA] INFORMATION : OpenGL Driver: 4.5.13447 Compatibility Profile Context 16.300.2311.0
(14:58:22.554) [FNA] INFORMATION : OpenGL Vendor: ATI Technologies Inc.
(14:58:22.554) [FNA] INFORMATION : MojoShader Profile: glsl120
(14:58:22.561) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(14:58:22.579) [Instancing] INFORMATION : Hardware instancing is enabled
(14:58:22.612) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(14:58:22.613) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(14:58:22.613) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(14:58:22.613) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(14:58:22.614) [SettingsManager] INFORMATION : VSync is on
(14:58:22.614) [SettingsManager] INFORMATION : Multisample count is 0
(14:58:22.684) [Threading] INFORMATION : Multithreading is disabled
(14:58:23.256) [Intro] INFORMATION : First draw done!
(14:58:23.967) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
(14:58:24.089) [StaticPreloader] INFORMATION : Music library initialized.
(14:58:24.100) [StaticPreloader] INFORMATION : Volume levels loaded.
(14:58:24.169) [StaticPreloader] INFORMATION : Animations filled.
(14:58:24.171) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
(14:58:24.171) [StaticPreloader] INFORMATION : World map pre-initialized.
(14:58:24.172) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
(14:58:24.479) [Intro] INFORMATION : Preloading complete.
(14:58:51.524) [Intro] INFORMATION : Level load complete.
(14:59:04.802) [Intro] INFORMATION : Intro is done and game is go!
(14:59:37.810) [Pause Menu] INFORMATION : Game restarted.
(15:00:31.090) [Pause Menu] INFORMATION : Game restarted.
(15:03:27.291) [Intro] INFORMATION : Level load complete.
(15:03:40.827) [Intro] INFORMATION : Intro is done and game is go!
(15:08:08.514) [Pause Menu] INFORMATION : Game restarted.
(15:08:08.555) [Unhandled Exception] ERROR : System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à FezGame.Components.BellHost.Update(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.<>c.<.cctor>b__100_1(IUpdateable updateable, GameTime gameTime)
   à Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   à FezGame.Fez.Update(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.Tick()
   à Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   à Microsoft.Xna.Framework.Game.Run()
   à FezGame.Program.MainInternal()
   à Common.Logger.Try(Action action)
(15:08:08.777) [FEZ] INFORMATION : Exiting.
```

That's 3 resets, and the crash happened when I selected the "Reset Run" menu a 4th time while being at the Bell (I failed the Bell inputs, that's an insta reset).
The previous resets were very quick, I didn't go farther than the intro.

**Comment by flibitijibibo** [comment] 2016-09-01 18:47
Not sure what this might be; we're in singlethreaded and I wasn't able to reproduce after a couple resets. Do you happen to remember when you reset while trying the bell tower? I think the only variation that might occur is when certain actions/animations are being done (such as ringing the bell).

**Comment by renaudbedard** [comment] 2016-09-02 01:28
The only way I can think of this bug happening in singlethreaded mode is because the old Update code in FNA was problematic and this is a symptom of it.
It was retooled recently, the Experimental branch has the latest FNA code and I'm pretty sure it's impossible for this to happen with how it works now... so optimistically closing this. :)

**Closed as completed by renaudbedard** 2016-09-02 01:28 UTC
